services:
  node-red:
    build:
      context: ./node-red
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1880-1890:1880-1890"
    user: "root:root"
    networks:
      - node-red-net
    volumes:
      - ./data:/data

volumes:
  data:
    driver: local
networks:
  node-red-net:
