################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    image: nodered/node-red:3.1.9
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./node-red-data:/data:rw

volumes:
  node-red-data:

networks:
  node-red-net:
